### Base URL
@baseUrl = http://localhost:3000

### 1. Home
GET {{baseUrl}}/
Content-Type: application/json


### 2. Create User
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Sanjay",
  "age": 30,
  "email":"sanjay@admin.com",
  "password":"123456"
}


### 3. Get All Users
GET {{baseUrl}}/users
Content-Type: application/json


### 4. Get User by ID
# Replace with actual _id
@REPLACE_USER_ID = 69ef662ff0bbf9ad3e8d583a
GET {{baseUrl}}/users/{{REPLACE_USER_ID}}
Content-Type: application/json


### 5. Update User
# Replace with actual _id
PUT {{baseUrl}}/users/{{REPLACE_USER_ID}}
Content-Type: application/json

{
  "name": "Updated Name",
  "age": 30
}


### 6. Delete User
# Replace with actual _id
DELETE {{baseUrl}}/users/{{REPLACE_USER_ID}}
Content-Type: application/json