### Base URL
@baseUrl = http://localhost:3000

##################################################
### 🔹 Home
GET {{baseUrl}}/

##################################################
### 🔹 Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John",
  "email": "ajohn@example.com",
  "password": "123456"
}

##################################################
### 🔹 Login User (Store Token)
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "123456"
}
> {%
    console.log("TOKEN:", response.body.token);
%}
##################################################
### 🔹 Get All Items
GET {{baseUrl}}/items

##################################################
### 🔐 Create Item (Protected)
POST {{baseUrl}}/items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Item 1",
  "price": 145
}

##################################################
### 🔐 Update Item (Protected)
PUT {{baseUrl}}/items/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Item",
  "price": 200
}

##################################################
### 🔹 Get Item Details
GET {{baseUrl}}/items/1