### Base URL
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsImVtYWlsIjoiYWpvaG5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NzU3NDUwMDksImV4cCI6MTc3NTgzMTQwOX0.dikdytwepxz-XoRxNNeZLQyYC6ODOWdXivfVz1pG9Gg
##################################################
### 🔹 Home
GET {{baseUrl}}/

##################################################
### 🔹 Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John",
  "email": "cjohn@example.com",
  "password": "123456"
}

##################################################
### 🔹 Login User (Store Token)
POST {{baseUrl}}/auth/login
Content-Type: application/json; charset=utf-8

{
  "email": "ajohn@example.com",
  "password": "123456"
}
# > {{#setToken response.body.token}}
##################################################
### 🔹 Get All Items
GET {{baseUrl}}/items

##################################################
### 🔐 Create Item (Protected)
POST {{baseUrl}}/items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Item 15E",
  "price": 145
}

##################################################
### 🔐 Update Item (Protected)
PUT {{baseUrl}}/items/25
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Item DPP",
  "price": 200
}

##################################################
### 🔹 Get Item Details
GET {{baseUrl}}/items/1


##################################################
### 🔐 Create Orders
POST {{baseUrl}}/customers/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "items": [
    { "item_id": 2, "quantity": 3 },
    { "item_id": 1, "quantity": 41 }
  ]
}
