### Base URL
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NTQsImVtYWlsIjoiYWpvaG5AZXhhbXBsZS5jb20iLCJpYXQiOjE3NzU3ODg4ODEsImV4cCI6MTc3NTg3NTI4MX0.zLIQ8bfJ1mDj80wl5sgUV1YGYXtlaALzBXdwMl74Dr4
##################################################
### 🔹 Home
GET {{baseUrl}}/

##################################################
### 🔹 Register User
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "name": "John",
  "email": "Fjohn@example.com",
  "password": "123456"
}

##################################################
### 🔹 Login User (Store Token)
POST {{baseUrl}}/auth/login
Content-Type: application/json; charset=utf-8

{
  "email": "ajohn@example.com",
  "password": "123456"
}
# > {{#setToken response.body.token}}
##################################################
### 🔹 Get All Items
GET {{baseUrl}}/items

##################################################
### 🔐 Create Item (Without Auth - Not Protected)
POST {{baseUrl}}/items
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "New Item 12DG",
  "price": 145
}

##################################################
### 🔐 Update Item (Protected)
PUT {{baseUrl}}/items/25
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Updated Item DPP",
  "price": 200
}

##################################################
### 🔹 Get Item Details
GET {{baseUrl}}/items/1


##################################################
### 🔐 Create Orders (Protected)
POST {{baseUrl}}/customers/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "items": [
    { "item_id": 2, "quantity": 3 },
    { "item_id": 1, "quantity": 51 }
  ]
}


############################################
### CREATE EMPLOYEE
POST {{baseUrl}}/employees
Content-Type: application/json

{
  "name": "John Doe",
  "salary": 50000,
  "email": "john01@example.com",
  "imageUrl": "https://example.com/image.jpg"
}

############################################
### GET ALL EMPLOYEES (Pagination)
GET {{baseUrl}}/employees?page=1&limit=10

############################################
### GET EMPLOYEE BY ID
GET {{baseUrl}}/employees/100

############################################
### UPDATE EMPLOYEE
PUT {{baseUrl}}/employees/100
Content-Type: application/json

{
  "name": "John Updated",
  "salary": 60000,
  "email": "engineering1452@gmail.com"
}

############################################
### DELETE EMPLOYEE
DELETE {{baseUrl}}/employees/1